### ISSUE TITLE
creality k1 reimage

### ISSUE THREAD

**Issue by richard-tx** [husjon/creality-k1#1]
Is there a way to reimage my k1 printer?

i loaded .30 and now it is forever messed up.

rich.andrews@gmail.com

**Comment by husjon** [comment]
Hi, the way it was done previously was to load an older firmware version onto a USB stick but rename the file so that the version number was higher than what was running on the printer itself.
F.ex let's say your printer is running `v1.2.9.30`, you can try to add a firmware image that is `v1.2.9.15` but rename the file so that it is named `v1.2.9.31`.
If this still works you should see it upgrade, the next thing to do is to reset the configuration.

You can also have a look at the video by aim6mac at https://www.youtube.com/watch?v=nbbp7NvvzTM

Please do let me know if it still works.

If this does not work anymore, Creality will be releasing an open source version of their firmware in September.
Their tweet can be found at https://twitter.com/Creality3dP/status/1682342838586204166

Hope this helps.

**Comment by richard-tx** [comment]
all attempts to go back to a previous firmware version have failed.  I returned the printer and got a new one.  Problem solved.  I destroyed all "upgrade" files.  Creality has removed klipper and fluidd adn klipper software from the latest firmware upgrade.
