### ISSUE TITLE
Will those cfgs run with 1.3.2.1 ?

### ISSUE THREAD

**Issue by cpietsch** [husjon/creality-k1#2]
Thank you for sharing your settings. Right now I am running V1.3.1.28 on my K1 (non Max), because the V1.3.2.1 from github was not installing from usb stick.
Are you running [V1.3.2.1](https://github.com/husjon/creality-k1/compare/original-config-1.3.2.1...main) with those cfgs?

**Comment by husjon** [comment]
Hi
Yeah, the config in the [original-config-1.3.2.1](https://github.com/husjon/creality-k1/tree/) branch is all from a fully factory reset K1 running v1.3.2.1
The config in main is just my additions from it.

~I just realized that I did not align the v1.3.2.1 branch correctly (to get a proper diff), but the content is correct.~
Branch has now been rebased so that it follows the timeline more correctly.

**Comment by husjon** [comment]
Closing the issue, please re-open if you have any further questions. :)
